resources:
  repositories:
    - repository: etonDigital
      type: github
      name: teechMe/etonDigital
      endpoint: 'GitHubServiceConnection'
      ref: refs/heads/master

pool:
  vmImage: 'windows-latest'

jobs:
- job: RunTests
  displayName: 'Run Cypress Tests'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: npm install
      displayName: 'Install dependencies'

    - script: npm run test:ci
      displayName: 'Run tests and merge reports'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'cypress\results\merged-results.xml'
        testRunTitle: 'Cypress Tests - $(Build.BuildNumber)'
      condition: succeededOrFailed()
      displayName: 'Publish Test Results'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Job Roles'
      inputs:
        pathtoPublish: 'cypress/fixtures/job_roles.txt'
        artifactName: 'JobRoles'