# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
  repositories:
    - repository: etonDigital  # Your reference name for this repo
      type: github
      name: teechMe/etonDigital  # GitHub format: 'owner/repo'
      endpoint: 'GitHubServiceConnection'  # Name of your GitHub service connection
      ref: refs/heads/master  # Default branch to clone

pool:
  name: self-hosted

jobs:
 - job: RunTests
   displayName: 'Run tests'
   strategy: 
      maxParallel: 1
   steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
      displayName: 'Install dependencies'

    # Install required reporters
    - script: npm install --save-dev mocha mocha-junit-reporter cypress-multi-reporters
      displayName: 'Install Reporters'

    # Debug: Show directory structure before tests
    - powershell: |
        Write-Host "Directory structure before test run:"
        Get-ChildItem -Recurse
      displayName: 'Pre-Run Directory Check'


    # Run Cypress with both reporters
    - script: npm run test:full
      displayName: 'Run Tests with Dual Reporting'
      continueOnError: true  # Continue even if tests fail


    # Debug: Verify files were created
    - powershell: |
        Write-Host "Test result files:"
        Get-ChildItem -Path cypress\results -Recurse
        if (!(Test-Path "cypress\results\junit\*.xml")) {
          Write-Host "##vso[task.logissue type=warning]No XML files found!"
        }
      displayName: 'Verify Test Results'


    # Publish to Test Plans > Runs
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'cypress\results\junit\*.xml'
        testRunTitle: 'Cypress Test Results - $(Build.BuildNumber)'
      condition: succeededOrFailed()
      displayName: 'Publish Test Results'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'cypress/reports/html'
        artifactName: 'CypressHTMLReport'
      condition: succeededOrFailed()
      displayName: 'Publish HTML Report'
      enabled: true