# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
  repositories:
    - repository: etonDigital  # Your reference name for this repo
      type: github
      name: teechMe/etonDigital  # GitHub format: 'owner/repo'
      endpoint: 'GitHubServiceConnection'  # Name of your GitHub service connection
      ref: refs/heads/master  # Default branch to clone

pool:
  name: self-hosted

jobs:
 - job: RunTests
   displayName: 'Run tests'
   strategy: 
      maxParallel: 1
   steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
      displayName: 'npm install'

    - script: |
        npx cypress run --spec cypress\e2e\*.cy.js --reporter junit --reporter-options "mochaFile=cypress/results/results-[hash].xml"
      displayName: 'Run Cypress Tests with JUnit Reporting'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'cypress/results/*.xml'
        mergeTestResults: true
        testRunTitle: 'Cypress Tests'
      condition: succeededOrFailed()
      displayName: 'Publish Test Results'
