# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
  repositories:
    - repository: etonDigital  # Your reference name for this repo
      type: github
      name: teechMe/etonDigital  # GitHub format: 'owner/repo'
      endpoint: 'GitHubServiceConnection'  # Name of your GitHub service connection
      ref: refs/heads/master  # Default branch to clone

pool:
  name: self-hosted

jobs:
 - job: RunTests
   displayName: 'Run tests'
   strategy: 
      maxParallel: 1
   steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
      displayName: 'Install dependencies'

    # Run Cypress with both reporters
    - script: |
        mkdir -p cypress/reports
        mkdir -p cypress/results/junit
        npx cypress run \
         --browser chrome --headless \
         --reporter cypress-mochawesome-reporter \
         --reporter-options "reportDir=cypress/reports,json=true,html=true" \
         --reporter junit \
         --reporter-options "mochaFile=cypress/results/junit/results-[hash].xml"
         --spec "cypress/e2e/*.cy.js"
      displayName: 'Run Cypress Tests'
      continueOnError: true  # Continue even if tests fail

    - powershell: |
        Write-Host "Generated test files:"
        Get-ChildItem -Path cypress/results/junit -Recurse -File
        if (!(Test-Path "cypress/results/junit/*.xml")) {
          throw "No JUnit XML files found!"
        }
      displayName: 'Verify XML Files Exist (Windows)'
    
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'cypress/results/junit/*.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)'
        mergeTestResults: true
        testRunTitle: 'Cypress Tests - $(Build.BuildNumber)'
      condition: succeededOrFailed()
      displayName: 'Publish Test Results'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'cypress/reports'
        artifactName: 'CypressHTMLReport'
      condition: succeededOrFailed()
      displayName: 'Publish HTML Report'